expand translation
buttercup/ui pull request #39
Opened 2021-03-07 17:10 UTC by sarashino

This PR depends on #38.
Expanding translation coverage for custom-field-type.
The implementation may evil as translation keys ain't hard coded and are generated with tagged template literals.
```
t(`custom-fields.change-type.${fieldTypeOption.title}`)
```

2021-03-08 17:05 UTC, perry-mitchell requested changes
Just a few minor changes..

2021-03-08 17:05 UTC, perry-mitchell commented on src/components/vault/EntryDetails.js
> +          text={t(`custom-fields.change-type.${fieldTypeOption.title}`)}
It would be better if this was 2 separate translations, one for "Change Type:" and another for the type itself.

2021-03-08 17:05 UTC, perry-mitchell commented on src/components/vault/EntryDetails.js
> +  { type: EntryPropertyValueType.OTP, title: 'otp', icon: 'time' }
Perhaps `title` should be changed to something like `i18n` to indicate that it's a key used for translations..?

2021-03-08 17:05 UTC, perry-mitchell commented on src/i18n/translations/ja.json
> +  "custom-fields": {
Could this be moved up, so it's alphabetical?

2021-03-09 06:05 UTC, sarashino commented
@perry-mitchell
Minor change requests have been fixed.

2021-03-09 06:15 UTC, sarashino commented
@perry-mitchell 
Change requests have been fixed. 🙇

2021-03-09 20:11 UTC, perry-mitchell approved these changes

2021-03-09 20:12 UTC, perry-mitchell commented
Thanks @sarashino! I'll merge

2021-03-09 20:12 UTC, merged